-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 12:49:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema empresareparto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresareparto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresareparto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `empresareparto` ;

-- -----------------------------------------------------
-- Table `empresareparto`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresareparto`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresareparto`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresareparto`.`solicitudes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NULL DEFAULT NULL,
  `fecha_solicitud` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente', 'procesando', 'completada') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `empresa_id` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `solicitudes_ibfk_1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `empresareparto`.`empresas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresareparto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresareparto`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitud_id` INT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `direccion_entrega` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_entrega` DATETIME NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'en camino', 'entregado') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `solicitud_id` (`solicitud_id` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`solicitud_id`)
    REFERENCES `empresareparto`.`solicitudes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresareparto`.`trabajadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresareparto`.`trabajadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` ENUM('moto', 'a pie') NULL DEFAULT NULL,
  `estado` ENUM('disponible', 'ocupado') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresareparto`.`asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresareparto`.`asignaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NULL DEFAULT NULL,
  `trabajador_id` INT NULL DEFAULT NULL,
  `fecha_asignacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado_entrega` ENUM('en camino', 'entregado', 'cancelado') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pedido_id` (`pedido_id` ASC) VISIBLE,
  INDEX `trabajador_id` (`trabajador_id` ASC) VISIBLE,
  CONSTRAINT `asignaciones_ibfk_1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `empresareparto`.`pedidos` (`id`),
  CONSTRAINT `asignaciones_ibfk_2`
    FOREIGN KEY (`trabajador_id`)
    REFERENCES `empresareparto`.`trabajadores` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresareparto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresareparto`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  `apellidos` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` ENUM('administrador', 'cliente', 'trabajador') NOT NULL,
  `empresa_id` INT NULL DEFAULT NULL,
  `trabajador_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `empresa_id` (`empresa_id` ASC) VISIBLE,
  INDEX `trabajador_id` (`trabajador_id` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `empresareparto`.`empresas` (`id`),
  CONSTRAINT `usuarios_ibfk_2`
    FOREIGN KEY (`trabajador_id`)
    REFERENCES `empresareparto`.`trabajadores` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
